version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      TERM: dumb
      CACHE_VERSION: 1
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    steps:
      - checkout
      - restore_cache:
          key: sc-bus-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}
      - run:
          name: "Download dependencies"
          command: ./mvnw -s .settings.xml -U --fail-never dependency:go-offline || true
      - run:
          name: "Install rootless Docker"
          command: |
            echo XDG_RUNTIME_DIR $XDG_RUNTIME_DIR
            curl -fsSL https://get.docker.com/rootless | sh > init.sh
            cat init.sh
            source <(grep '^export' init.sh)
            PATH=$HOME/bin:$PATH dockerd-rootless.sh --experimental --storage-driver vfs &
            sleep 1
            DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock docker info || ls -la $XDG_RUNTIME_DIR
      - save_cache:
          key: sc-bus-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}
          paths:
            - ~/.m2
      - run:
          name: "Running build"
          command: ./mvnw -s .settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install -U -P sonar -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} ~/junit/ \;
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ~/junit/
          destination: artifacts
      - store_test_results:
          path: ~/junit/
          destination: testartifacts
