[[addressing]]
= Addressing Instances
:page-section-summary-toc: 1

[[addressing-an-instance]]
== Addressing an Instance

Each instance of the application has a service ID, whose value can be set with
`spring.cloud.bus.id` and whose value is expected to be a colon-separated list of
identifiers, in order from least specific to most specific. The default value is
constructed from the environment as a combination of the `spring.application.name` and
`server.port` (or `spring.application.index`, if set). The default value of the ID is
constructed in the form of `app:index:id`, where:

* `app` is the `vcap.application.name`, if it exists, or `spring.application.name`
* `index` is the `vcap.application.instance_index`, if it exists,
`spring.application.index`, `local.server.port`, `server.port`, or `0` (in that order).
* `id` is the `vcap.application.instance_id`, if it exists, or a random value.

The HTTP endpoints accept a "`destination`" path parameter, such as
`/busrefresh/customers:9000`, where `destination` is a service ID. If the ID
is owned by an instance on the bus, it processes the message, and all other instances
ignore it.

[[addressing-all-instances-of-a-service]]
== Addressing All Instances of a Service

The "`destination`" parameter is used in a Spring `PathMatcher` (with the path separator
as a colon -- `:`) to determine if an instance processes the message. Using the example
from earlier, `/busenv/customers:**` targets all instances of the
"`customers`" service regardless of the rest of the service ID.

[[service-id-must-be-unique]]
== Service ID Must Be Unique

The bus tries twice to eliminate processing an event -- once from the original
`ApplicationEvent` and once from the queue. To do so, it checks the sending service ID
against the current service ID. If multiple instances of a service have the same ID,
events are not processed. When running on a local machine, each service is on a different
port, and that port is part of the ID. Cloud Foundry supplies an index to differentiate.
To ensure that the ID is unique outside Cloud Foundry, set `spring.application.index` to
something unique for each instance of a service.

